title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: subpage
      files:
        type: files
      fields:    # Add a "fields" section within the "sidebar" section
        type: fields
        fields:
          subpage_drawer_name:
            label: Subpages Title  # Customize the label as needed
            type: text

