name: Deploy to Uberspace

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: /
          remote_path: /home/instudio/html/dev/arandor-app
          remote_host: vanness.uberspace.de
          remote_user: instudio
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
